version: 0.2

phases:

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR via NAT Gateway..."
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION
      
  build:
    commands:
      - echo "Build started on `date`"
      - docker build -t $REPOSITORY_URI:latest ./services/users-api
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      
  post_build:
    commands:
      - echo "Pushing the Docker images via NAT Gateway..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Creating ECS deployment file..."
      - printf '[{"name":"users-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      
artifacts:
  files:
    - imagedefinitions.json
