version: 0.2

phases:

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR via NAT Gateway..."
      - aws ecr aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 488369868153.dkr.ecr.us-east-2.amazonaws.com
      
  build:
    commands:
      - echo "Build started on `date`"
      - docker build -t 488369868153.dkr.ecr.us-east-2/users-api:latest ./services/users-api
      - docker tag 488369868153.dkr.ecr.us-east-2.amazonaws.com/users-api:latest 488369868153.dkr.ecr.us-east-2.amazonaws.com/users-api:latest
      
  post_build:
    commands:
      - echo "Pushing the Docker images via NAT Gateway..."
      - docker push 488369868153.dkr.ecr.us-east-2/users-api:latest
      - echo "Creating ECS deployment file..."
      - printf '[{"name":"users-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      
artifacts:
  files:
    - imagedefinitions.json
